# Generated by Django 3.0.3 on 2020-03-19 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIServer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todos',
            old_name='keep',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='todos',
            old_name='title',
            new_name='todoid',
        ),
    ]
