# Generated by Django 3.0.3 on 2020-03-19 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIServer', '0002_auto_20200319_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='todoid',
            field=models.IntegerField(),
        ),
    ]
